#!/usr/bin/python3
import sys
from math import sqrt


arg1 = str(sys.argv[1])

File = open(arg1, 'r')

lines = File.readlines()

for line in lines:
    
    num = int(line)
    a = sqrt(num)
    if a % 2 == 0:
        print("{:d}={:d}*{:d}".format(num, num//i, i))
        continue

    i = 3
    for i in range(i, a, 2):
        if num % i == 0:
            break
    print("{:d}={:d}*{:d}".format(num, num//i, i))
