#!/usr/bin/python3
import sys
from decimal import *


arg1 = str(sys.argv[1])

File = open(arg1, 'r')

lines = File.readlines()

for line in lines:
    n = len(line)
    getcontext().prec = n
    
    num = int(line)
    a = int(Decimal(num).sqrt())

    
    for i in range(a, a-n, -2):
        if num % i == 0:
            break
    print("{:d}={:d}*{:d}".format(num, num//i, i))
